In [22]:
import pandas as pd
import numpy as np
coffee=pd.read_csv('./warmup-data/coffee.csv')

In [42]:
# coffee.loc[[0,1],'Units Sold']=np.nan
# coffee=coffee.fillna(10000) # filled the data when the value is null

coffee.loc[[2,3],'Units Sold']=np.nan
coffee.dropna() # drop null role
# coffee.head()

          Day Coffee Type  Units Sold
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0